#pragma rtGlobals=3
#pragma version=1.0

// ExportIgorGraphLoader.ipf
// Generated by make_loader.py from eig_allowlist.py (pattern fingerprint 86d2b62e00). Do not edit by hand.
//
// Draws a figure written by export_igor (mpl_to_igor.py). Install this file once; no per-figure .ipf is needed.
//   LoadPythonFigure()                            macro: choose the .h5 in a dialog (also in the Macros menu)
//   LoadPythonFigure_exec()                       the same, as a function (returns 0 on success)
//   LoadPythonFigure_exec(h5Path="C:\\folder\\fig1.h5")       explicit path
//   LoadPythonFigure_exec(pathName="mySymPath", h5Path="fig1.h5")
//   EIG_SelfTest()                                tests the allowlist; prints PASS / FAIL
//
// SAFETY: the .h5 file carries drawing commands as text. Execute runs anything it is given (it can even
// reach the Windows command line via ExecuteScriptText), so opening an untrusted file must never run it.
// This loader executes ONLY commands that fully match the allowlist (EIG_IsAllowed). Everything is
// validated BEFORE anything is loaded or executed; if one command is rejected, nothing is executed.
// Execute is used in exactly one place (EIG_RunCommand). Every command it runs is echoed in the history.

//-------------------------------------------//
// Main entry
//-------------------------------------------//
Function LoadPythonFigure_exec([h5Path, pathName])
	String h5Path, pathName

	Variable fileID, i, nBad, err
	String wn, c, metaList, name
	DFREF saveDF = GetDataFolderDFR()

	if (!ParamIsDefault(pathName))
		HDF5OpenFile/P=$pathName/R/Z fileID as h5Path
	elseif (!ParamIsDefault(h5Path))
		HDF5OpenFile/R/Z fileID as h5Path
	else
		HDF5OpenFile/R/I/Z fileID as ""
	endif
	if (V_flag != 0)
		Print "LoadPythonFigure: HDF5OpenFile failed or was canceled."
		return -1
	endif

	Wave/T meta = EIG_ReadText(fileID, "igor_meta")
	Wave/T wlist = EIG_ReadText(fileID, "igor_waves")
	Wave/T cmds = EIG_ReadText(fileID, "igor_cmds")
	if (numpnts(meta) == 0 || numpnts(wlist) == 0 || numpnts(cmds) == 0)
		Print "LoadPythonFigure: no embedded figure found (igor_meta / igor_waves / igor_cmds)."
		HDF5CloseFile fileID
		return -1
	endif

	metaList = ""
	for (i = 0; i < numpnts(meta); i += 1)
		metaList += meta[i] + ";"
	endfor
	name = StringByKey("name", metaList, "=")
	if (!GrepString(name, "^[A-Za-z][A-Za-z0-9_]{0,15}$"))
		Print "LoadPythonFigure: invalid figure name in the file. Nothing was executed."
		HDF5CloseFile fileID
		return -1
	endif
	if (CmpStr(StringByKey("format", metaList, "="), "1") != 0)
		Print "LoadPythonFigure: unsupported file format version. Update ExportIgorGraphLoader.ipf."
		HDF5CloseFile fileID
		return -1
	endif

	// 1) validate every wave name and every command BEFORE loading or executing anything
	nBad = 0
	for (i = 0; i < numpnts(wlist); i += 1)
		wn = wlist[i]
		if (!GrepString(wn, "^[A-Za-z][A-Za-z0-9_]{0,30}$"))
			Printf "LoadPythonFigure: REJECTED wave name %d: %s\r", i + 1, EIG_Head(wn, 80)
			nBad += 1
		endif
	endfor
	for (i = 0; i < numpnts(cmds); i += 1)
		c = cmds[i]
		if (!EIG_IsAllowed(c))
			Printf "LoadPythonFigure: REJECTED command %d: %s\r", i + 1, EIG_Head(c, 150)
			nBad += 1
		endif
	endfor
	if (nBad > 0)
		Printf "LoadPythonFigure: %d item(s) were rejected. Nothing was loaded or executed.\r", nBad
		HDF5CloseFile fileID
		return -1
	endif

	// 2) load the data waves into root:<name>
	SetDataFolder root:
	NewDataFolder/O/S $name
	for (i = 0; i < numpnts(wlist); i += 1)
		wn = wlist[i]
		HDF5LoadData/O/Z/Q/IGOR=-1 fileID, wn
		if (V_flag != 0)
			Printf "LoadPythonFigure: HDF5LoadData failed for %s\r", wn
			HDF5CloseFile fileID
			SetDataFolder saveDF
			return -1
		endif
	endfor
	HDF5CloseFile fileID

	// 3) run the (already validated) commands; the current data folder is root:<name>
	for (i = 0; i < numpnts(cmds); i += 1)
		c = cmds[i]
		err = EIG_RunCommand(c)
		if (err != 0)
			Printf "LoadPythonFigure: command %d failed (V_flag=%d): %s\r", i + 1, err, EIG_Head(c, 150)
			SetDataFolder saveDF
			return -1
		endif
	endfor

	KillDataFolder/Z root:EIG_tmp
	SetDataFolder saveDF
	Printf "LoadPythonFigure: '%s' was drawn (%d commands).\r", name, numpnts(cmds)
	return 0
End

// Macro for the Macros menu / command line: choose the .h5 in a dialog and draw it.
Macro LoadPythonFigure()	// style-allow: Macro
	LoadPythonFigure_exec()
End

//-------------------------------------------//
// The only place where Execute is used
//-------------------------------------------//
Function EIG_RunCommand(cmd)
	String cmd

	if (!EIG_IsAllowed(cmd))			// defense in depth: check again right before Execute
		return -999
	endif
	Execute/Z cmd						// style-allow: Execute (cmd has just passed EIG_IsAllowed)
	return V_flag
End

//-------------------------------------------//
// Allowlist
//-------------------------------------------//
Function EIG_IsAllowed(cmd)
	String cmd

	Variable i, n = strlen(cmd)
	if (n == 0 || n > 2400)
		return 0
	endif
	if (GrepString(cmd, "[^ -~]"))		// anything except printable ASCII (control characters, non-ASCII)
		return 0
	endif
	Wave/T pats = EIG_Patterns()
	for (i = 0; i < numpnts(pats); i += 1)
		if (GrepString(cmd, pats[i]))
			return 1
		endif
	endfor
	return 0
End

Function/S EIG_Head(s, n)
	String s
	Variable n

	if (strlen(s) > n)
		return s[0, n - 1] + "..."
	endif
	return s
End

// Full-match regular expressions, one per command type (generated from eig_allowlist.PATTERNS)
Function/WAVE EIG_Patterns()
	Make/FREE/T/N=15 pats
	String s

	// DoWindow/K
	s = "^DoWindow/K [A-Za-z][A-Za-z0-9_]{0,30}$"
	pats[0] = s
	// DoWindow/F
	s = "^DoWindow/F [A-Za-z][A-Za-z0-9_]{0,30}$"
	pats[1] = s
	// Display
	s = "^Display/N=[A-Za-z][A-Za-z0-9_]{0,30}(?:/W=\\(-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+("
	s += "?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?\\))?(?: [A-Za-z][A-Za-z0-9_]{0,30} vs [A-Za-z][A-Za-z0-9_]{0,30})?$"
	pats[2] = s
	// AppendToGraph
	s = "^AppendToGraph/W=[A-Za-z][A-Za-z0-9_]{0,30} [A-Za-z][A-Za-z0-9_]{0,30} vs [A-Za-z][A-Za-z0-9_]{0,30}$"
	pats[3] = s
	// AppendImage
	s = "^AppendImage/W=[A-Za-z][A-Za-z0-9_]{0,30} [A-Za-z][A-Za-z0-9_]{0,30} vs \\{[A-Za-z][A-Za-z0-9_]{0,30},[A-Za-z][A-Za-z0-9_]{0,30}\\}$"
	pats[4] = s
	// ModifyGraph
	s = "^ModifyGraph/W=[A-Za-z][A-Za-z0-9_]{0,30} (?:margin\\((?:left|bottom|top|right)\\)=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|gfSize=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|width=-?"
	s += "[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|height=(?:-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|\\{Aspect,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?\\})|tick=-?[0-9]+(?:\\.[0-9]+)?(?:[eE]["
	s += "-+]?[0-9]+)?|mirror=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|standoff=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|(?:log|grid)\\((?:bottom|left)\\)=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0"
	s += "-9]+)?|(?:mode|marker|msize|mrkThick|opaque|lSize|lStyle)\\([A-Za-z][A-Za-z0-9_]{0,30}\\)=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|(?:lSize|lStyle)=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?"
	s += "[0-9]+)?|rgb\\([A-Za-z][A-Za-z0-9_]{0,30}\\)=\\(-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?\\)|(?:font"
	s += "|gFont)=\"(?:Arial|Helvetica|Times New Roman|Times|Courier New|Courier|Calibri|Verdana|Tahoma|Segoe UI|Georgia|Cambria|Meiryo|Yu Gothic|MS Gothic|MS PGothic|default)\"|gridRGB\\((?:bo"
	s += "ttom|left)\\)=\\(-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?\\)|(?:gridStyle|lblPos|lblMargin|logLTri"
	s += "p|logHTrip)\\((?:bottom|left)\\)=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?)(?:,(?:margin\\((?:left|bottom|top|right)\\)=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|gfSize=-?[0-9]+(?:\\.[0"
	s += "-9]+)?(?:[eE][-+]?[0-9]+)?|width=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|height=(?:-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|\\{Aspect,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?\\})"
	s += "|tick=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|mirror=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|standoff=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|(?:log|grid)\\((?:bottom|left)\\)="
	s += "-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|(?:mode|marker|msize|mrkThick|opaque|lSize|lStyle)\\([A-Za-z][A-Za-z0-9_]{0,30}\\)=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|(?:lSize|lStyle"
	s += ")=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|rgb\\([A-Za-z][A-Za-z0-9_]{0,30}\\)=\\(-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-"
	s += "9]+)?(?:[eE][-+]?[0-9]+)?\\)|(?:font|gFont)=\"(?:Arial|Helvetica|Times New Roman|Times|Courier New|Courier|Calibri|Verdana|Tahoma|Segoe UI|Georgia|Cambria|Meiryo|Yu Gothic|MS Gothic|"
	s += "MS PGothic|default)\"|gridRGB\\((?:bottom|left)\\)=\\(-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?\\)|(?"
	s += ":gridStyle|lblPos|lblMargin|logLTrip|logHTrip)\\((?:bottom|left)\\)=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?))*$"
	pats[5] = s
	// ModifyImage
	s = "^ModifyImage/W=[A-Za-z][A-Za-z0-9_]{0,30} [A-Za-z][A-Za-z0-9_]{0,30} ctab=\\{-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,[A-Za-z][A-Za-z0-9_]"
	s += "{0,30},[01]\\}(?:,log=1)?$"
	pats[6] = s
	// AppendMatrixContour
	s = "^AppendMatrixContour/W=[A-Za-z][A-Za-z0-9_]{0,30} [A-Za-z][A-Za-z0-9_]{0,30} vs \\{[A-Za-z][A-Za-z0-9_]{0,30},[A-Za-z][A-Za-z0-9_]{0,30}\\}$"
	pats[7] = s
	// ModifyContour
	s = "^ModifyContour/W=[A-Za-z][A-Za-z0-9_]{0,30} [A-Za-z][A-Za-z0-9_]{0,30}, (?:manLevels=[A-Za-z][A-Za-z0-9_]{0,30}|rgbLines=\\(-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0"
	s += "-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?\\)|ctabLines=\\{-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,[A-Za-z][A-Za"
	s += "-z0-9_]{0,30},[01]\\}|labels=[0-4]|labelFSize=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|fill=[01]|rgbFill=\\(-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+"
	s += "]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?\\)|cTabFill=\\{-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,[A-Za-z][A-Za-z0-9_]{0,30},[01"
	s += "]\\})(?:,(?:manLevels=[A-Za-z][A-Za-z0-9_]{0,30}|rgbLines=\\(-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9"
	s += "]+)?\\)|ctabLines=\\{-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,[A-Za-z][A-Za-z0-9_]{0,30},[01]\\}|labels=[0-4]|labelFSize=-?[0-9]+(?:\\.[0-9]+"
	s += ")?(?:[eE][-+]?[0-9]+)?|fill=[01]|rgbFill=\\(-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?\\)|cTabFill="
	s += "\\{-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,[A-Za-z][A-Za-z0-9_]{0,30},[01]\\}))*$"
	pats[8] = s
	// ErrorBars
	s = "^ErrorBars/W=[A-Za-z][A-Za-z0-9_]{0,30}(?:/(?:T|L|X|Y)=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?)*(?:/RGB=\\(-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-"
	s += "+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?\\))? [A-Za-z][A-Za-z0-9_]{0,30}, (?:X|Y|XY) wave=\\([A-Za-z][A-Za-z0-9_]{0,30},[A-Za-z][A-Za-z0-9_]{0,30}\\)(?:, wave=\\([A-Za-z]["
	s += "A-Za-z0-9_]{0,30},[A-Za-z][A-Za-z0-9_]{0,30}\\))?$"
	pats[9] = s
	// SetAxis
	s = "^SetAxis/W=[A-Za-z][A-Za-z0-9_]{0,30} (?:bottom|left) -?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?,-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?$"
	pats[10] = s
	// Label
	s = "^Label/W=[A-Za-z][A-Za-z0-9_]{0,30} (?:bottom|left) \"(?:[^\"\\\\]|\\\\.)*\"$"
	pats[11] = s
	// Legend
	s = "^Legend/W=[A-Za-z][A-Za-z0-9_]{0,30}/N=[A-Za-z][A-Za-z0-9_]{0,30}(?:/F=[012])?(?:/M=[01])?(?:/H=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?)?(?:/E=[012])?/A=(?:LT|MT|RT|LC|MC|RC|LB|M"
	s += "B|RB)(?:/X=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?)?(?:/Y=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?)? \"(?:[^\"\\\\]|\\\\.)*\"$"
	pats[12] = s
	// ColorScale
	s = "^ColorScale/C/N=[A-Za-z][A-Za-z0-9_]{0,30}(?:/F=[012])?(?:/E=[012])?(?:/A=(?:LT|MT|RT|LC|MC|RC|LB|MB|RB))?(?:/X=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?)?(?:/Y=-?[0-9]+(?:\\.[0-9]+"
	s += ")?(?:[eE][-+]?[0-9]+)?)?(?: (?:image=[A-Za-z][A-Za-z0-9_]{0,30}|log=[01]|logLTrip=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|lblMargin=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|widt"
	s += "h=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|height=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|heightPct=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|widthPct=-?[0-9]+(?:\\.[0-9]+)?(?:[e"
	s += "E][-+]?[0-9]+)?|frame=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|nticks=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|fsize=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|font=\"(?:Arial|Helv"
	s += "etica|Times New Roman|Times|Courier New|Courier|Calibri|Verdana|Tahoma|Segoe UI|Georgia|Cambria|Meiryo|Yu Gothic|MS Gothic|MS PGothic|default)\"|side=[12]|tickLen=-?[0-9]+(?:\\.[0-9]"
	s += "+)?(?:[eE][-+]?[0-9]+)?|minor=[01])(?:,(?:image=[A-Za-z][A-Za-z0-9_]{0,30}|log=[01]|logLTrip=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|lblMargin=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0"
	s += "-9]+)?|width=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|height=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|heightPct=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|widthPct=-?[0-9]+(?:\\.[0"
	s += "-9]+)?(?:[eE][-+]?[0-9]+)?|frame=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|nticks=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|fsize=-?[0-9]+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|font=\"(?"
	s += ":Arial|Helvetica|Times New Roman|Times|Courier New|Courier|Calibri|Verdana|Tahoma|Segoe UI|Georgia|Cambria|Meiryo|Yu Gothic|MS Gothic|MS PGothic|default)\"|side=[12]|tickLen=-?[0-9]"
	s += "+(?:\\.[0-9]+)?(?:[eE][-+]?[0-9]+)?|minor=[01]))*)?(?: \"(?:[^\"\\\\]|\\\\.)*\")?$"
	pats[13] = s
	// Redimension
	s = "^Redimension/U/W [A-Za-z][A-Za-z0-9_]{0,30}$"
	pats[14] = s
	return pats
End

//-------------------------------------------//
// Reading text datasets from the .h5
//-------------------------------------------//
// Returns a free text wave with one element per line.
// Tries the string dataset <baseName> first, then the char-code dataset <baseName>_codes.
Function/WAVE EIG_ReadText(fileID, baseName)
	Variable fileID
	String baseName

	Variable i, n, count
	String line, codesName
	DFREF saveDF = GetDataFolderDFR()
	NewDataFolder/O/S root:EIG_tmp

	KillWaves/Z $baseName
	HDF5LoadData/O/Z/Q fileID, baseName
	if (V_flag == 0)
		Wave/T/Z tw = $baseName
		if (WaveExists(tw))
			Duplicate/FREE tw, resultA
			KillWaves/Z tw
			SetDataFolder saveDF
			return resultA
		endif
	endif

	Make/FREE/T/N=0 resultB
	codesName = baseName + "_codes"
	KillWaves/Z $codesName
	HDF5LoadData/O/Z/Q fileID, codesName
	if (V_flag == 0)
		Wave/Z cw = $codesName
		if (WaveExists(cw))
			n = numpnts(cw)
			count = 0
			line = ""
			for (i = 0; i < n; i += 1)
				if (cw[i] == 0)
					InsertPoints count, 1, resultB
					resultB[count] = line
					count += 1
					line = ""
				else
					line += num2char(cw[i])
				endif
			endfor
			KillWaves/Z cw
		endif
	endif
	SetDataFolder saveDF
	return resultB
End

//-------------------------------------------//
// Self test of the allowlist (commands that must pass / must be rejected)
//-------------------------------------------//
Function EIG_SelfTest()

	Variable i, nOK = 0, nNG = 0
	String longCmd
	Make/FREE/T/N=42 good
	Make/FREE/T/N=53 bad

	good[0] = "DoWindow/K fig1"
	good[1] = "DoWindow/F fig1"
	good[2] = "Display/N=fig1"
	good[3] = "Display/N=fig1/W=(40,40,328,256)"
	good[4] = "Display/N=fig1/W=(40,40,328,256) fig1_t0_y vs fig1_t0_x"
	good[5] = "Display/N=fig1 fig1_t0_y vs fig1_t0_x"
	good[6] = "AppendToGraph/W=fig1 fig1_t1_y vs fig1_t1_x"
	good[7] = "AppendImage/W=fig1 fig1_i0_z vs {fig1_i0_xe,fig1_i0_ye}"
	good[8] = "ModifyGraph/W=fig1 margin(left)=43,margin(bottom)=37,margin(top)=14,margin(right)=14"
	good[9] = "ModifyGraph/W=fig1 gfSize=14,width=226.772,height={Aspect,0.8}"
	good[10] = "ModifyGraph/W=fig1 tick=2,mirror=1,standoff=0"
	good[11] = "ModifyGraph/W=fig1 log(bottom)=1"
	good[12] = "ModifyGraph/W=fig1 grid(left)=1"
	good[13] = "ModifyGraph/W=fig1 mode(fig1_t0_y)=3,rgb(fig1_t0_y)=(54998,10023,10280),marker(fig1_t0_y)=19,msize(fig1_t0_y)=1.5,mrkThick(fig1_t0_y)=1,opaque(fig1_t0_y)=0,lSize(fig1_t0_y)=1.5"
	good[14] = "ModifyImage/W=fig1 fig1_i0_z ctab={1,1e+06,fig1_i0_ct,0},log=1"
	good[15] = "ModifyImage/W=fig1 fig1_i0_z ctab={-0.5,25,Rainbow,1}"
	good[16] = "ErrorBars/W=fig1/T=1/L=0.8/X=2/Y=2 fig1_t0_y, Y wave=(fig1_t0_eyp,fig1_t0_eyn)"
	good[17] = "ErrorBars/W=fig1/T=0/L=1/RGB=(0,0,0) fig1_t1_y, XY wave=(fig1_t1_ex,fig1_t1_ex), wave=(fig1_t1_ey,fig1_t1_ey)"
	good[18] = "SetAxis/W=fig1 left 2.5,-0.5"
	good[19] = "Label/W=fig1 bottom \"\\\\f02Q\\\\f00\\\\Bz\\\\M [nm\\\\S-1\\\\M]\""
	good[20] = "Label/W=fig1 left \"semi;colon and \\\"quote\\\" inside \\u00C5\""
	good[21] = "Legend/W=fig1/N=legend0/F=0/A=RT \"\\\\s(fig1_t1_y) fit\\rdata\""
	good[22] = "Legend/W=fig1/N=legend0/F=0/M=1/A=RT \"\\\\s(fig1_t1_y) fit\""
	good[23] = "Legend/W=fig1/N=legend0/F=2/M=1/H=40/E=0/A=LB/X=2/Y=3 \"x\""
	good[24] = "ColorScale/C/N=cs0/A=MC image=fig1_i0_z,log=1"
	good[25] = "ColorScale/C/N=cs0 logLTrip=0.1"
	good[26] = "ColorScale/C/N=cs0 \"Intensity [a.u.]\""
	good[27] = "ColorScale/C/N=cs0 lblMargin=15"
	good[28] = "ColorScale/C/N=cs0/X=56.00/Y=16.00"
	good[29] = "ColorScale/C/N=cs0/F=0/E=2/A=LT/X=84.5/Y=12.3 image=fig1_i0_z,log=1,width=15,height=120,frame=0,nticks=5,fsize=10,font=\"Arial\",lblMargin=5"
	good[30] = "ColorScale/C/N=cs0/F=0/E=1/A=RC/X=0/Y=0 image=fig1_i0_z,heightPct=100,widthPct=5,frame=0"
	good[31] = "ModifyGraph/W=fig1 font=\"Arial\""
	good[32] = "ModifyGraph/W=fig1 gFont=\"Yu Gothic\""
	good[33] = "ModifyGraph/W=fig1 grid(bottom)=2,gridRGB(bottom)=(45232,45232,45232),gridStyle(bottom)=5"
	good[34] = "ModifyGraph/W=fig1 lStyle(fig1_t0_y)=3,gridRGB(left)=(45232,45232,45232),gridStyle(left)=0,lblPos(bottom)=34,lblMargin(left)=2"
	good[35] = "ModifyGraph/W=fig1 logLTrip(bottom)=1e+10,logHTrip(left)=0.5"
	good[36] = "Redimension/U/W fig1_i0_ct"
	good[37] = "AppendMatrixContour/W=fig1 fig1_c0_z vs {fig1_c0_x,fig1_c0_y}"
	good[38] = "ModifyContour/W=fig1 fig1_c0_z, manLevels=fig1_c0_lv,rgbLines=(0,0,0),labels=0"
	good[39] = "ModifyContour/W=fig1 fig1_c0_z, manLevels=fig1_c0_lv,ctabLines={0,1.05,fig1_c0_ct,0},labels=3,labelFSize=9"
	good[40] = "ModifyContour/W=fig1 fig1_c0_z, fill=1,cTabFill={0,1.05,fig1_c0_ct,0}"
	good[41] = "ModifyGraph/W=fig1 lSize=1.5,lStyle=3"

	bad[0] = "ExecuteScriptText \"cmd /c calc\""
	bad[1] = "KillWaves/A"
	bad[2] = "KillDataFolder root:"
	bad[3] = "Execute \"Print 1\""
	bad[4] = "Make/O w=1"
	bad[5] = "ModifyGraph/W=fig1 rgb(x)=(0,0,0);KillWaves/A"
	bad[6] = "ModifyGraph/W=fig1 mode(x)=1;ModifyGraph/W=fig1 mode(y)=2"
	bad[7] = "ModifyGraph/W=fig1 foo(x)=1"
	bad[8] = "ModifyGraph/W=fig1 mode(x)=1,"
	bad[9] = "ModifyGraph mode(x)=3"
	bad[10] = "Label/W=fig1 bottom \"a\";KillWaves/A;\"b\""
	bad[11] = "Label/W=fig1 bottom \"a\\\""
	bad[12] = "Label/W=fig1 bottom \"a\"" + num2char(10) + "KillWaves/A"
	bad[13] = "Label/W=fig1 bottom \"a\"" + num2char(13) + "KillWaves/A"
	bad[14] = "Label/W=fig1 right \"a\""
	bad[15] = "Display/N=fig1 a vs b;Print 1"
	bad[16] = "Display/N=\"fig1\""
	bad[17] = "Display/N=fig1 root:a vs b"
	bad[18] = "SetAxis/W=fig1 bottom 1,2;DoWindow/K x"
	bad[19] = "SetAxis/W=fig1 bottom 1e,2"
	bad[20] = "DoWindow/K root:fig1"
	bad[21] = "DoWindow/K fig 1"
	bad[22] = "DoWindow/K aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
	bad[23] = "AppendImage/W=fig1 a vs {b}"
	bad[24] = "Legend/W=fig1/N=l/A=ZZ \"x\""
	bad[25] = "ColorScale/C/N=cs0 image=z;KillWaves/A"
	bad[26] = "ErrorBars/W=fig1/Q y, Y wave=(a,b)"
	bad[27] = "ModifyGraph/W=fig1 font=\"Evil;KillWaves/A\""
	bad[28] = "ModifyGraph/W=fig1 font=\"Arial\";KillWaves/A"
	bad[29] = "ModifyGraph/W=fig1 gFont=\"Evil;KillWaves/A\""
	bad[30] = "ModifyGraph/W=fig1 gFont=\"Arial Black\""
	bad[31] = "ModifyGraph/W=fig1 gFont=Arial"
	bad[32] = "ModifyGraph/W=fig1 font=Arial"
	bad[33] = "ColorScale/C/N=cs0 foo=1"
	bad[34] = "ColorScale/C/N=cs0 image=z;KillWaves/A"
	bad[35] = "ColorScale/C/N=cs0 font=\"Evil;Kill\""
	bad[36] = "ColorScale/K/N=cs0"
	bad[37] = "ColorScale/C/N=cs0/Z=1 image=z"
	bad[38] = "Legend/W=fig1/N=l/M=7/A=RT \"x\""
	bad[39] = "Legend/W=fig1/N=l/K/A=RT \"x\""
	bad[40] = "Display/N=fig1/W=(1,2,3)"
	bad[41] = "Display/N=fig1/W=(1,2,3,4);Print 1"
	bad[42] = "Redimension/N=1000000000 w"
	bad[43] = "AppendMatrixContour/W=fig1 z vs {x,y};KillWaves/A"
	bad[44] = "AppendMatrixContour/W=fig1 root:z vs {x,y}"
	bad[45] = "ModifyContour/W=fig1 z, manLevels=w;KillWaves/A"
	bad[46] = "ModifyContour/W=fig1 z, foo=1"
	bad[47] = "ModifyContour/W=fig1 z, labels=9"
	bad[48] = "ModifyContour/W=fig1 z, fill=1,"
	bad[49] = "ModifyGraph/W=fig1 lSize=1.5;KillWaves/A"
	bad[50] = "HDF5LoadData fileID, \"x\""
	bad[51] = ""
	bad[52] = "Label/W=fig1 bottom \"\u00C5\""

	for (i = 0; i < numpnts(good); i += 1)
		if (EIG_IsAllowed(good[i]))
			nOK += 1
		else
			Printf "FAIL (should be allowed): %s\r", good[i]
			nNG += 1
		endif
	endfor
	for (i = 0; i < numpnts(bad); i += 1)
		if (EIG_IsAllowed(bad[i]))
			Printf "FAIL (should be rejected): %s\r", bad[i]
			nNG += 1
		else
			nOK += 1
		endif
	endfor

	// a command that is too long (Execute accepts at most 2500 bytes)
	longCmd = "Label/W=fig1 bottom \""
	for (i = 0; i < 300; i += 1)
		longCmd += "aaaaaaaaaa"
	endfor
	longCmd += "\""
	if (EIG_IsAllowed(longCmd))
		Print "FAIL (should be rejected): a 3000-byte command"
		nNG += 1
	else
		nOK += 1
	endif

	Printf "EIG_SelfTest (pattern fingerprint 86d2b62e00): %d passed, %d failed\r", nOK, nNG
	if (nNG == 0)
		Print "EIG_SelfTest: ALL PASS"
	endif
	return nNG
End
