#!/usr/bin/env python3
"""
make_loader.py
==============

固定の Igor ローダー ExportIgorGraphLoader.ipf を生成する。

    python make_loader.py [出力先ディレクトリ]      # 既定: ../igor/ か カレント

使う側は、このファイルを Igor に1回入れるだけ（図ごとの .ipf は不要）:
    LoadPythonFigure()      → ファイル選択ダイアログで、export_igor が書いた .h5 を選ぶ

許可リストの正規表現は eig_allowlist.py から生成する。パターンを変えたら、必ずこのスクリプトを
再実行してローダーを作り直す（パターンの指紋が .ipf の先頭に入るので、テストで古さを検出できる）。
"""

from __future__ import annotations

import hashlib
import os
import sys

from export_igorgraph import eig_allowlist as al

SELFTEST_LONG_LIMIT = 300  # これより長い見本は、自己検査では別の方法（ループで作る）で試す


def patterns_fingerprint() -> str:
    h = hashlib.sha1("\n".join(rx for _, rx in al.PATTERNS).encode("utf-8")).hexdigest()
    return h[:10]


def igor_expr(sample: str) -> str:
    """Python の文字列を、同じ文字列になる Igor の式にする。制御文字は num2char、非ASCIIは \\uXXXX。"""
    pieces, cur = [], ""

    def flush():
        nonlocal cur
        if cur:
            pieces.append('"' + cur + '"')
            cur = ""

    for ch in sample:
        o = ord(ch)
        if o < 32:
            flush()
            pieces.append(f"num2char({o})")
        elif o > 126:
            cur += "\\u%04X" % o
        elif ch == "\\":
            cur += "\\\\"
        elif ch == '"':
            cur += '\\"'
        else:
            cur += ch
    flush()
    return " + ".join(pieces) if pieces else '""'


def build() -> str:
    L: list[str] = []
    a = L.append
    fp = patterns_fingerprint()

    a("#pragma rtGlobals=3")
    a("#pragma version=1.0")
    a("")
    a("// ExportIgorGraphLoader.ipf")
    a(f"// Generated by make_loader.py from eig_allowlist.py (pattern fingerprint {fp}). Do not edit by hand.")
    a("//")
    a("// Draws a figure written by export_igor (mpl_to_igor.py). Install this file once; no per-figure .ipf is needed.")
    a("//   LoadPythonFigure()                            macro: choose the .h5 in a dialog (also in the Macros menu)")
    a("//   LoadPythonFigure_exec()                       the same, as a function (returns 0 on success)")
    a("//   LoadPythonFigure_exec(h5Path=\"C:\\\\folder\\\\fig1.h5\")       explicit path")
    a("//   LoadPythonFigure_exec(pathName=\"mySymPath\", h5Path=\"fig1.h5\")")
    a("//   EIG_SelfTest()                                tests the allowlist; prints PASS / FAIL")
    a("//")
    a("// SAFETY: the .h5 file carries drawing commands as text. Execute runs anything it is given (it can even")
    a("// reach the Windows command line via ExecuteScriptText), so opening an untrusted file must never run it.")
    a("// This loader executes ONLY commands that fully match the allowlist (EIG_IsAllowed). Everything is")
    a("// validated BEFORE anything is loaded or executed; if one command is rejected, nothing is executed.")
    a("// Execute is used in exactly one place (EIG_RunCommand). Every command it runs is echoed in the history.")
    a("")
    a("//-------------------------------------------//")
    a("// Main entry")
    a("//-------------------------------------------//")
    a("Function LoadPythonFigure_exec([h5Path, pathName])")
    a("\tString h5Path, pathName")
    a("")
    a("\tVariable fileID, i, nBad, err")
    a("\tString wn, c, metaList, name")
    a("\tDFREF saveDF = GetDataFolderDFR()")
    a("")
    a("\tif (!ParamIsDefault(pathName))")
    a("\t\tHDF5OpenFile/P=$pathName/R/Z fileID as h5Path")
    a("\telseif (!ParamIsDefault(h5Path))")
    a("\t\tHDF5OpenFile/R/Z fileID as h5Path")
    a("\telse")
    a("\t\tHDF5OpenFile/R/I/Z fileID as \"\"")
    a("\tendif")
    a("\tif (V_flag != 0)")
    a("\t\tPrint \"LoadPythonFigure: HDF5OpenFile failed or was canceled.\"")
    a("\t\treturn -1")
    a("\tendif")
    a("")
    a("\tWave/T meta = EIG_ReadText(fileID, \"igor_meta\")")
    a("\tWave/T wlist = EIG_ReadText(fileID, \"igor_waves\")")
    a("\tWave/T cmds = EIG_ReadText(fileID, \"igor_cmds\")")
    a("\tif (numpnts(meta) == 0 || numpnts(wlist) == 0 || numpnts(cmds) == 0)")
    a("\t\tPrint \"LoadPythonFigure: no embedded figure found (igor_meta / igor_waves / igor_cmds).\"")
    a("\t\tHDF5CloseFile fileID")
    a("\t\treturn -1")
    a("\tendif")
    a("")
    a("\tmetaList = \"\"")
    a("\tfor (i = 0; i < numpnts(meta); i += 1)")
    a("\t\tmetaList += meta[i] + \";\"")
    a("\tendfor")
    a("\tname = StringByKey(\"name\", metaList, \"=\")")
    a(f"\tif (!GrepString(name, \"{al.igor_literal(al.RE_FIGURE_NAME)}\"))")
    a("\t\tPrint \"LoadPythonFigure: invalid figure name in the file. Nothing was executed.\"")
    a("\t\tHDF5CloseFile fileID")
    a("\t\treturn -1")
    a("\tendif")
    a("\tif (CmpStr(StringByKey(\"format\", metaList, \"=\"), \"1\") != 0)")
    a("\t\tPrint \"LoadPythonFigure: unsupported file format version. Update ExportIgorGraphLoader.ipf.\"")
    a("\t\tHDF5CloseFile fileID")
    a("\t\treturn -1")
    a("\tendif")
    a("")
    a("\t// 1) validate every wave name and every command BEFORE loading or executing anything")
    a("\tnBad = 0")
    a("\tfor (i = 0; i < numpnts(wlist); i += 1)")
    a("\t\twn = wlist[i]")
    a(f"\t\tif (!GrepString(wn, \"{al.igor_literal(al.RE_WAVE_NAME)}\"))")
    a("\t\t\tPrintf \"LoadPythonFigure: REJECTED wave name %d: %s\\r\", i + 1, EIG_Head(wn, 80)")
    a("\t\t\tnBad += 1")
    a("\t\tendif")
    a("\tendfor")
    a("\tfor (i = 0; i < numpnts(cmds); i += 1)")
    a("\t\tc = cmds[i]")
    a("\t\tif (!EIG_IsAllowed(c))")
    a("\t\t\tPrintf \"LoadPythonFigure: REJECTED command %d: %s\\r\", i + 1, EIG_Head(c, 150)")
    a("\t\t\tnBad += 1")
    a("\t\tendif")
    a("\tendfor")
    a("\tif (nBad > 0)")
    a("\t\tPrintf \"LoadPythonFigure: %d item(s) were rejected. Nothing was loaded or executed.\\r\", nBad")
    a("\t\tHDF5CloseFile fileID")
    a("\t\treturn -1")
    a("\tendif")
    a("")
    a("\t// 2) load the data waves into root:<name>")
    a("\tSetDataFolder root:")
    a("\tNewDataFolder/O/S $name")
    a("\tfor (i = 0; i < numpnts(wlist); i += 1)")
    a("\t\twn = wlist[i]")
    a("\t\tHDF5LoadData/O/Z/Q/IGOR=-1 fileID, wn")
    a("\t\tif (V_flag != 0)")
    a("\t\t\tPrintf \"LoadPythonFigure: HDF5LoadData failed for %s\\r\", wn")
    a("\t\t\tHDF5CloseFile fileID")
    a("\t\t\tSetDataFolder saveDF")
    a("\t\t\treturn -1")
    a("\t\tendif")
    a("\tendfor")
    a("\tHDF5CloseFile fileID")
    a("")
    a("\t// 3) run the (already validated) commands; the current data folder is root:<name>")
    a("\tfor (i = 0; i < numpnts(cmds); i += 1)")
    a("\t\tc = cmds[i]")
    a("\t\terr = EIG_RunCommand(c)")
    a("\t\tif (err != 0)")
    a("\t\t\tPrintf \"LoadPythonFigure: command %d failed (V_flag=%d): %s\\r\", i + 1, err, EIG_Head(c, 150)")
    a("\t\t\tSetDataFolder saveDF")
    a("\t\t\treturn -1")
    a("\t\tendif")
    a("\tendfor")
    a("")
    a("\tKillDataFolder/Z root:EIG_tmp")
    a("\tSetDataFolder saveDF")
    a("\tPrintf \"LoadPythonFigure: '%s' was drawn (%d commands).\\r\", name, numpnts(cmds)")
    a("\treturn 0")
    a("End")
    a("")
    a("// Macro for the Macros menu / command line: choose the .h5 in a dialog and draw it.")
    a("Macro LoadPythonFigure()\t// style-allow: Macro")
    a("\tLoadPythonFigure_exec()")
    a("End")
    a("")
    a("//-------------------------------------------//")
    a("// The only place where Execute is used")
    a("//-------------------------------------------//")
    a("Function EIG_RunCommand(cmd)")
    a("\tString cmd")
    a("")
    a("\tif (!EIG_IsAllowed(cmd))\t\t\t// defense in depth: check again right before Execute")
    a("\t\treturn -999")
    a("\tendif")
    a("\tExecute/Z cmd\t\t\t\t\t\t// style-allow: Execute (cmd has just passed EIG_IsAllowed)")
    a("\treturn V_flag")
    a("End")
    a("")
    a("//-------------------------------------------//")
    a("// Allowlist")
    a("//-------------------------------------------//")
    a("Function EIG_IsAllowed(cmd)")
    a("\tString cmd")
    a("")
    a("\tVariable i, n = strlen(cmd)")
    a(f"\tif (n == 0 || n > {al.MAX_COMMAND_BYTES})")
    a("\t\treturn 0")
    a("\tendif")
    a("\tif (GrepString(cmd, \"[^ -~]\"))\t\t// anything except printable ASCII (control characters, non-ASCII)")
    a("\t\treturn 0")
    a("\tendif")
    a("\tWave/T pats = EIG_Patterns()")
    a("\tfor (i = 0; i < numpnts(pats); i += 1)")
    a("\t\tif (GrepString(cmd, pats[i]))")
    a("\t\t\treturn 1")
    a("\t\tendif")
    a("\tendfor")
    a("\treturn 0")
    a("End")
    a("")
    a("Function/S EIG_Head(s, n)")
    a("\tString s")
    a("\tVariable n")
    a("")
    a("\tif (strlen(s) > n)")
    a("\t\treturn s[0, n - 1] + \"...\"")
    a("\tendif")
    a("\treturn s")
    a("End")
    a("")
    a(f"// Full-match regular expressions, one per command type (generated from eig_allowlist.PATTERNS)")
    a("Function/WAVE EIG_Patterns()")
    a(f"\tMake/FREE/T/N={len(al.PATTERNS)} pats")
    a("\tString s")
    a("")
    for k, (label, rx) in enumerate(al.PATTERNS):
        a(f"\t// {label}")
        chunks = al.chunk_regex(rx, 180)
        for j, ch in enumerate(chunks):
            a(f"\ts {'=' if j == 0 else '+='} \"{al.igor_literal(ch)}\"")
        a(f"\tpats[{k}] = s")
    a("\treturn pats")
    a("End")
    a("")
    a("//-------------------------------------------//")
    a("// Reading text datasets from the .h5")
    a("//-------------------------------------------//")
    a("// Returns a free text wave with one element per line.")
    a("// Tries the string dataset <baseName> first, then the char-code dataset <baseName>_codes.")
    a("Function/WAVE EIG_ReadText(fileID, baseName)")
    a("\tVariable fileID")
    a("\tString baseName")
    a("")
    a("\tVariable i, n, count")
    a("\tString line, codesName")
    a("\tDFREF saveDF = GetDataFolderDFR()")
    a("\tNewDataFolder/O/S root:EIG_tmp")
    a("")
    a("\tKillWaves/Z $baseName")
    a("\tHDF5LoadData/O/Z/Q fileID, baseName")
    a("\tif (V_flag == 0)")
    a("\t\tWave/T/Z tw = $baseName")
    a("\t\tif (WaveExists(tw))")
    a("\t\t\tDuplicate/FREE tw, resultA")
    a("\t\t\tKillWaves/Z tw")
    a("\t\t\tSetDataFolder saveDF")
    a("\t\t\treturn resultA")
    a("\t\tendif")
    a("\tendif")
    a("")
    a("\tMake/FREE/T/N=0 resultB")
    a("\tcodesName = baseName + \"_codes\"")
    a("\tKillWaves/Z $codesName")
    a("\tHDF5LoadData/O/Z/Q fileID, codesName")
    a("\tif (V_flag == 0)")
    a("\t\tWave/Z cw = $codesName")
    a("\t\tif (WaveExists(cw))")
    a("\t\t\tn = numpnts(cw)")
    a("\t\t\tcount = 0")
    a("\t\t\tline = \"\"")
    a("\t\t\tfor (i = 0; i < n; i += 1)")
    a("\t\t\t\tif (cw[i] == 0)")
    a("\t\t\t\t\tInsertPoints count, 1, resultB")
    a("\t\t\t\t\tresultB[count] = line")
    a("\t\t\t\t\tcount += 1")
    a("\t\t\t\t\tline = \"\"")
    a("\t\t\t\telse")
    a("\t\t\t\t\tline += num2char(cw[i])")
    a("\t\t\t\tendif")
    a("\t\t\tendfor")
    a("\t\t\tKillWaves/Z cw")
    a("\t\tendif")
    a("\tendif")
    a("\tSetDataFolder saveDF")
    a("\treturn resultB")
    a("End")
    a("")
    a("//-------------------------------------------//")
    a("// Self test of the allowlist (commands that must pass / must be rejected)")
    a("//-------------------------------------------//")
    good = al.GOOD_SAMPLES
    bad = [s for s in al.BAD_SAMPLES if len(s) <= SELFTEST_LONG_LIMIT]
    a("Function EIG_SelfTest()")
    a("")
    a("\tVariable i, nOK = 0, nNG = 0")
    a("\tString longCmd")
    a(f"\tMake/FREE/T/N={len(good)} good")
    a(f"\tMake/FREE/T/N={len(bad)} bad")
    a("")
    for k, s in enumerate(good):
        a(f"\tgood[{k}] = {igor_expr(s)}")
    a("")
    for k, s in enumerate(bad):
        a(f"\tbad[{k}] = {igor_expr(s)}")
    a("")
    a("\tfor (i = 0; i < numpnts(good); i += 1)")
    a("\t\tif (EIG_IsAllowed(good[i]))")
    a("\t\t\tnOK += 1")
    a("\t\telse")
    a("\t\t\tPrintf \"FAIL (should be allowed): %s\\r\", good[i]")
    a("\t\t\tnNG += 1")
    a("\t\tendif")
    a("\tendfor")
    a("\tfor (i = 0; i < numpnts(bad); i += 1)")
    a("\t\tif (EIG_IsAllowed(bad[i]))")
    a("\t\t\tPrintf \"FAIL (should be rejected): %s\\r\", bad[i]")
    a("\t\t\tnNG += 1")
    a("\t\telse")
    a("\t\t\tnOK += 1")
    a("\t\tendif")
    a("\tendfor")
    a("")
    a("\t// a command that is too long (Execute accepts at most 2500 bytes)")
    a("\tlongCmd = \"Label/W=fig1 bottom \\\"\"")
    a("\tfor (i = 0; i < 300; i += 1)")
    a("\t\tlongCmd += \"aaaaaaaaaa\"")
    a("\tendfor")
    a("\tlongCmd += \"\\\"\"")
    a("\tif (EIG_IsAllowed(longCmd))")
    a("\t\tPrint \"FAIL (should be rejected): a 3000-byte command\"")
    a("\t\tnNG += 1")
    a("\telse")
    a("\t\tnOK += 1")
    a("\tendif")
    a("")
    a(f"\tPrintf \"EIG_SelfTest (pattern fingerprint {fp}): %d passed, %d failed\\r\", nOK, nNG")
    a("\tif (nNG == 0)")
    a("\t\tPrint \"EIG_SelfTest: ALL PASS\"")
    a("\tendif")
    a("\treturn nNG")
    a("End")
    return "\r\n".join(L) + "\r\n"


def main(argv=None):
    if isinstance(argv, (str, os.PathLike)):  # 文字列のパスをそのまま渡してもよい（1文字目だけを使ってしまう誤りの防止）
        argv = [os.fspath(argv)]
    out_dir = (argv or sys.argv[1:] or ["."])[0]
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "ExportIgorGraphLoader.ipf")
    text = build()
    with open(path, "w", newline="") as f:
        f.write(text)
    print(f"wrote {path} ({len(text.splitlines())} lines, fingerprint {patterns_fingerprint()})")
    return path


if __name__ == "__main__":
    main()
